name: Build and push Docker images
on:
  push:
    branches:
      - 'main'
      - 'testing/**'
      - 'feature/**'
      - 'hotfix/**'

jobs:
  build-and-push:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build base
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: maxkratz/texlive:base
      #     platforms: linux/amd64,linux/arm64,linux/arm/v7
      - name: npm build
        run: npm run build-image
      - name: Tag Docker image
        run: docker tag spliit2:latest maxkratz/spliit2:latest
      - name: Push Docker image
        run: docker push maxkratz/spliit2:latest
